title: Xinwei(Rachel) He
logo: /asset/img/profilepic.png
description: >
  <ul>
    <li>
      <a href="https://www.linkedin.com/in/YOUR-LINKEDIN-USERNAME/" target="_blank">
        LinkedIn
      </a>
    </li>
    <li>
      Email: <a href="mailto:rachelhexinwei@gmail.com">rachelhexinwei@gmail.com</a>
    </li>
    <li>
      I love playing drums and piano!
    </li>
  </ul>
theme: jekyll-theme-minimal
